name: bites
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0-163.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dots_indicator: ^2.0.0
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
