name: bites
description: Discover local food around you.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0-163.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dots_indicator: ^2.0.0
  shared_preferences:
  geolocator:
  geoflutterfire2:
  google_maps_flutter: ^2.2.5
  heroicons:
  provider:
  cached_network_image: ^3.2.3
  flutter_dotenv: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.0"
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/data/italian_cities.json
    - .env

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true
